[package]
name = "drivechain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.27.1"
kv = { version = "0.22.0", features = ["bincode-value"] }
hyper = { version = "0.14.15", features = ["full"] }
tokio = { version = "1", features = ["full"] }
base64 = "0.13"
serde_json = "1.0.71"
serde = { version = "1.0.130", features = ["derive"] }
hex = "0.4.3"
rand = "0.8.4"
bincode = "1.3.3"
